### ISSUE TITLE
Invalid utf-8 strings are invalidly parsed as valid json

### ISSUE THREAD

**Issue by Julien-Blanc-tgcm** [CPPAlliance/json#11]
See attached file. It should not be parsed correctly.

[invalid_json.json.gz](https://github.com/vinniefalco/json/files/3884966/invalid_json.json.gz)

**Comment by vinniefalco** [comment]
Yes, the parser does not perform utf8 validation. I'm not sure if it should. The place to do it is here:
https://github.com/vinniefalco/json/blob/develop/include/boost/json/impl/basic_parser.ipp#L497

**Comment by WPMGPRoSToTeMa** [comment]
[The JSON Data Interchange Syntax](https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) says (emphasis mine):
> A string is a **_sequence of Unicode code points_** wrapped with quotation marks (U+0022).

So I think it should be validated since invalid UTF-8 is just a sequence of **UTF-8** code **units**, but not also a sequence of **Unicode** code **points**.

**Comment by vinniefalco** [comment]
To do this we need to

* modify `detail::count_unescaped` to stop when it encounters a character with the high-bit set.

* check if `(c & 0x80) != 0` here: https://github.com/CPPAlliance/json/blob/fcdf8856512b51109ec4fe6792a40302bb30768c/include/boost/json/basic_parser.hpp#L768

* then, if we have at least 3 more characters, implement "fast" utf-8 validation (all bytes present), otherwise do a `goto` into a new state where we handle one character at a time and check for the end of the stream.

This looks doable, but it will add an additional branch. We could put it after all the other checks for escapes, and then it would be zero cost. However, users will then complain that they want the parser to accept invalid UTF-8....

**Comment by WPMGPRoSToTeMa** [comment]
> However, users will then complain that they want the parser to accept invalid UTF-8....

Similar to accepting comments in JSON.

**Comment by vinniefalco** [comment]
> Similar to accepting comments in JSON.

Yes and then if we parse and ignore comments, users will 1. want a way to turn it off, and 2. ask to have the comments preserved when serializing.

**Comment by WPMGPRoSToTeMa** [comment]
Probably it would be better to add a precondition that input string should be valid utf-8 (and same for `json::string`).

**Comment by vinniefalco** [comment]
Well, we can expect all we want but if the JSON comes from an untrusted network source that won't do much good. As for `json::string`, yes the caller is responsible for putting only valid UTF-8 in the string.

**Comment by WPMGPRoSToTeMa** [comment]
Yep, in this case `parse` should accept something like `valid_utf8_string_view` instead :smile: (or just an overload). And well, that overload can be added in future when there will be a standard way to pre-validate utf-8 strings.

**Comment by vinniefalco** [comment]
Well I think in this case we can afford to always do the validation, and provide a run-time switch to turn it off, without affecting performance.

**Comment by sdkrystian** [comment]
Implemented in d98b565887834bca73fde2cc8f0216de6c7992f8. Validation is enabled by default, but can be disabled by passing `parse_options` to `parser::parser`.
