### ISSUE TITLE
Vcpkg support

### ISSUE THREAD

**Issue by sdkrystian** [CPPAlliance/json#156]

**Comment by vinniefalco** [comment]
What does "vcpkg support" mean? I prefer that the people who are interested in having the package for a particular package manager, who know the package system well, are the ones who maintain the package. I don't know much about vcpkg, and I'm not enthusiastic about learning. If Boost.JSON is good enough and users find it helpful then they can package it.

I also don't want to be promoting Boost.JSON in a package before it has gone through review, because we are calling it "Boost" JSON but it has not been accepted yet, and that's bad form.

**Comment by vinniefalco** [comment]
Boost is already packaged, and if/when Boost.JSON is accepted, will get packaged right along with all the other Boost libraries. So there is not really anything actionable here.

**Comment by sdkrystian** [comment]
@vinniefalco Copy that
