### ISSUE TITLE
Enhancement request: equality comparison function/operator

### ISSUE THREAD

**Issue by hadrielk** [CPPAlliance/json#313]
I may be overlooking something, but I can't find a way to compare two `json::value`s. There's no `operator==()` for that type, nor any named function to perform a deep comparison. Correct?

I think that's a fairly common requirement/use-case for this type of library, and was surprising to not have.

Apologies if I just didn't see it. I'm still learning the API while testing it.

**Comment by vinniefalco** [comment]
That's right, there's no deep comparison, largely because objects are unordered. To perform the comparison would require allocating memory, which means it could throw. That is why `value` is _SemiRegular_, and not _Regular_. I have a function I use for testing which performs the comparison, it assumes that the order for objects is the same: https://github.com/CPPAlliance/json/blob/develop/test/test.hpp#L970

Obviously, this is not general and relies on implementation details (which is OK for the tests). We might add a general version in the future, as an example program.

**Comment by hadrielk** [comment]
Huh. What requires allocating memory for a deep comparison? The test function you cited doesn't appear to do so.(?)

If that has to be done I get your point, but it feels really weird to me to not have comparison built into it - even if only via a named member or free function.

**Comment by vinniefalco** [comment]
A library-quality equality function would have to either sort objects by key in order to perform the comparison (or else perform N^2 comparisons).

**Comment by vinniefalco** [comment]
> Sorry for belaboring this topic.

No, you are doing 100% the right thing to be asking questions. Are you going to participate in the Boost formal review? It starts September 14th, just sign up on the mailing list:
https://www.boost.org/community/groups.html#main

Your feedback would be incredibly helpful, and you could bring up this point of the equality (which we will probably need to address).

**Comment by hadrielk** [comment]
Yup, I'm on the mailing list and was planning to submit a review - it's how I got here. :)

**Comment by hadrielk** [comment]
Oops, sorry for sending to the list - I thought that's what you wanted. I didn't notice you closed this with an actual fix. Thanks!
